"""add source id to norms

Revision ID: 5a80a2d23ee4
Revises: 9e723e860c2d
Create Date: 2026-08-13 20:37:14.912649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a80a2d23ee4'
down_revision: Union[str, Sequence[str], None] = '9e723e860c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('norms', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_norms_source_id'), 'norms', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_norms_source_id'), table_name='norms')
    op.drop_column('norms', 'source_id')
    # ### end Alembic commands ###
