"""create norms table

Revision ID: 7d2cebfa2d05
Revises: 
Create Date: 2026-08-12 17:22:56.183455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2cebfa2d05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_type', sa.String(), nullable=False),
    sa.Column('act_number', sa.Integer(), nullable=False),
    sa.Column('agency_unit', sa.String(), nullable=False),
    sa.Column('publication', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_norms_id'), 'norms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_norms_id'), table_name='norms')
    op.drop_table('norms')
    # ### end Alembic commands ###
